added missing strict-mode pragmas, specified Node compatibility
required for Node v4 compatibility:

> SyntaxError: Block-scoped declarations (let, const, function, class)
> not yet supported outside strict mode

however, turns out Node v4 isn't supported anyway, so this is mostly for
consistency